### ISSUE TITLE
Rewrite GitHub Actions workflow for testing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-ogc#43]
@CAMOBAP can you please help rewrite the GHA workflows in this repository with latest practice? Thanks!

**Comment by ronaldtse** [comment]
The current GHA workflows rely on Python and lots of custom code.

e.g.
```yaml
      - name: Metanorma compile *nix
        if: matrix.os != 'windows-latest'
        run: |
          source doctypes.env
          for template in $DOCTYPES
          do
            bundle exec metanorma new test/$template --type $TYPE --doctype $template --template . --overwrite
            if [ -f test/${template}/document.adoc ]
            then
              bundle exec metanorma compile --no-install-fonts test/${template}/document.adoc
            else
              for docfile in test/${template}/*.adoc
              do
                bundle exec metanorma compile --no-install-fonts $docfile
              done
            fi
          done
```

In the new GHA workflows, we have Metanorma actions, e.g.

```yaml
      - uses: actions-mn/setup@master

      - uses: actions-mn/cli/site-gen@main
        with:
          agree-to-terms: true
```
